apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bricklink-scraping
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:mribrgr/bricklink-scraping.git
    path: deploy/chart/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: bricklink-scraping
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # syncOptions:
    # - CreateNamespace=true
