---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: bricklink-scraping
spec:
  encryptedData:
    .dockerconfigjson: AgC4d2izwPJopF/qZ+VdkbNfl92asOw2R019LBDGRYSM4ewweynGA1FvVKHFuGpqYm+QOKSXNbZGBCiI2as2AffOS1KmhB0jX48m1sW+Ks6k2FiQ7tIsK5UPwAF/KZ/puGD/hRGHqf1QQ5PEYsEu3fNXl+6DSOozfSaNWS+iLaU+FH1BSw9E92DPOdPksLDrgASgpBgXQFcEA/WcFabdoTtvrb05aZiV93jG10/I2/cMoBat023pNrtYFG9hDFUwqVNWLvmWZLcvF9ZcUfVIpC7lMaXyTvoW4565Q5fpsu4IgRH4MSP3A0x8989QjlunaFdGXfi/oOXzSBXX4J4Bc8TDhIrETnZgEc5ezzJio28vvJZO0FjUkcLyrvoMrxyZRZwEluoLcDQXKhfwFAgKW9RxgONLVaNrPF+/B7yufctn1ZKH751YOoSwP7ZxaCHC0OwdFQqSJj2wFE1O1b8L+yjRxcgY0WrSNOBMmy7YVVBgHMfzm60BzFILGWfv1X1AB50Su9JX9v2UvoUlZQwrOxMpYKEAIRUccuad0jZf/fLrEznkuixinmyaDNpW/od7VXnMuMdBpavMRfmP2A6Nc9my5OFiKBlan91irbyEGuV9xB5htDEQwf/AJGi+jthv42ZjqJSwXeTbLTDR+VVtAUUSdXkbYCIWQNFwboVMDjolE30C4olJez/e+5LINNvc+KkP/OWft0kZUsomIVT0XB0rTgdlpLnWEa/3j2LLxQt/TJcZrcOD/KQne2X8qKQIe7jyYsFu+p8E2+CVMxrc7HGcXmACnLQP7sBBqmBCt6/Qqbl2me/h7Bcs1Wkd6WNR3IFmKZO9WprrNbLa7V5rCliPzz6pXZ98xSapVUk61gYFecMjk8ucf8vQt6KiunKmWzXEakaOvmjsP5ztVXrXRIvjcriXMdNc/y0cqbDV
  template:
    metadata:
      name: ghcr-secret
      namespace: bricklink-scraping
    type: kubernetes.io/dockerconfigjson
